name: CI

on: [push, pull_request]

env:
  DATABASE_URL: "https://fake.com"
  NEXTAUTH_URL: "http://localhost:3000"
  ADMIN_PASSWORD: "https://fake1.com"
  NEXTAUTH_SECRET: "fake" 
  GOOGLE_CLIENT_SECRET: "fake"
  GOOGLE_CLIENT_ID: "fake"
  GOOGLE_APP_CRID: "./"
  GOOGLE_SHEET_ID: "fakeID" 
  EMAILS: "fake@gamil.com"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install Dependencies
        run: yarn install

      - name: Typecheck
        run: yarn run typecheck

      - name: Lint
        run: yarn run lint

      - name: Print Environment Variable
        run: echo $MY_ENV_VAR
